package cn.zhumingwu.dms.domain;

import java.util.Date;

public class UserMobile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile.mobile
     *
     * @return the value of tb_mobile.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile.mobile
     *
     * @param mobile the value for tb_mobile.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile.time
     *
     * @return the value of tb_mobile.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile.time
     *
     * @param time the value for tb_mobile.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}