package cn.zhumingwu.dms.dao.mybatis;

import cn.zhumingwu.dms.domain.UserMobile;

public interface UserMobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile
     *
     * @mbggenerated
     */
    int insert(UserMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile
     *
     * @mbggenerated
     */
    int insertSelective(UserMobile record);
}